main        1
struct      2
int         3
char        4
for         5
while       6
printf      7
scanf       8
if          9
else        10
return      11
true        12
false       13
(           14
)           15